{% set name = "skorch" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7081a0c9ab2361d524826f90c84b04a74cf55338c2b2028fa59a2e39a9019e43

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.13.3
    - pytorch >=2.6.0
    - scikit-learn >=0.22.0
    - scipy >=1.1.0
    - tabulate >=0.7.7
    - tqdm >=4.14.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - numpy

about:
  home: https://github.com/dnouri/skorch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A scikit-learn compatible neural network library that wraps pytorch
  doc_url: https://skorch.readthedocs.io/en/latest/
  dev_url: https://github.com/dnouri/skorch

extra:
  recipe-maintainers:
    - BenjaminBossan
    - dhirschfeld
