{% set name = "skorch" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fddd2cd0de345b5f2e19f55b0fd5446e16d67ddba8a3e4c1a838e64e48cc531b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy >=1.13.3
    - pytorch
    - scikit-learn >=0.22.0
    - scipy >=1.1.0
    - tabulate >=0.7.7
    - tqdm >=4.14.0

test:
  imports:
    - numpy

about:
  home: https://github.com/dnouri/skorch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A scikit-learn compatible neural network library that wraps pytorch
  doc_url: https://skorch.readthedocs.io/en/latest/
  dev_url: https://github.com/dnouri/skorch

extra:
  recipe-maintainers:
    - BenjaminBossan
    - dhirschfeld
