{% set name = "skorch" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ec8c9144da95a633ff13db8b769011ff958cdc5c2b4cff09ada8f9a4e6fb6a6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - python >=3.5
    - numpy >=1.13.3
    - pyyaml >=3.12
    - setuptools
    - scikit-learn >=0.19.1
    - scipy >=0.19.0
    - tabulate >=0.7.7
    - tqdm >=4.14.0

test:
  imports:
    - numpy

about:
  home: https://github.com/dnouri/skorch
  license: BSD-3
  license_family: BSD
  license_file: LICENSE
  summary: A scikit-learn compatible neural network library that wraps pytorch
  doc_url: https://skorch.readthedocs.io/en/latest/
  dev_url: https://github.com/dnouri/skorch

extra:
  recipe-maintainers:
    - dhirschfeld
