travis:
  secure:
    BINSTAR_TOKEN: HjGVseRqaJX7zYyl3W8JoBj7bp99A6EnXDk8/WOF/Q5H3ma6WpddPxoDL772NapzJQffWafpellLFWxZKiGBJKFpx+2tF8ZCkrjcNmkwNjjBSYVvearLjGi2wsuY+UIVCr8+OBj5qX1v5Sl1vT1Ig8VwBOSi/LtfuFsgRzUcUJgHq0Y0xq8uCVLtG/WyKqjL7VR530Qy1POnrOxLpMS85T4KFAca0+AWagwxuzbcAb7tou422tlD7dgOaKc13P8yBLxfkmCEz0bJc94J7g9w0azT2SYycdLRUh8WVypWyNqDHs/JTWYaZkJFG7E53bgeUa2twA1QHCJwZjFAxuSwzjuOp0+TDXg+IaE8vHfL890fxNaFGVe9TPPaYseJeu/EipR004w8fRCV4YEV16fmcfmgydrEF3gLjgNu2wdkKag1pSnqgP7PykykkynlE1QA8nrkUkK/JdGBM7Bc4loBncAEF9Y4OITLrvBqHIDV6/KMZ+EUVV+s7vgfT9oS2saiU9A/7DST/NAtseVoivrNcmXzX5lFyJy1RDFF4dPy7LEBCzyml5hsY+JhxNkeQvilR/Fzbg+zRIdgZtlTU/4bztak+qJvFmP4cqrGwioT3l0xOm4GT3ult5usypuegpM0aefZMxjcXvawDisGH0u6xsoo5lm/Jesws8RNbDPUveI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
